export {default as Homepage} from './homepage/homepage'
export {default as InProgress} from './inProgress/inProgress'
export {default as AboutMe} from './aboutMe/aboutMe'
export {default as MyWork} from './myWork/myWork'
export {default as FindMe} from './findMe/findMe'
export {default as EachWork} from './eachWork/eachWork'