export {default as NavBar} from './navbar/navbar'
export {default as OpeningAnim} from './OpeningAnim/openingAnim'
export {default as ClosingAnim} from './closingAnim/closingAnim'
export { default as StyledJumbotron } from './jumbotron/jumbotron'
export {default as TaskContainer} from './tasksContainer/taskContainer'
export {default as Homepage} from './homepage/homepage'
export {default as InProgress} from './inProgress/inProgress'